title: JtD OpenSCAD Template
description: A starter template for a Jekyll site…
theme: just-the-docs
color_scheme: openscad-light
baseurl: "/just-the-docs-template-openscad"
permalink: pretty
repository: "CameronBrooks11/just-the-docs-template-openscad"

defaults:
  - scope:
      path: "" # all files since we are already inside the docs directory
      type: pages # target is page files
    values:
      layout: "default" # use the default layout for all unspecified pages

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

mermaid:
  version: "11.8.1" # Must an available version from https://cdn.jsdelivr.net/npm/mermaid/

aux_links:
  Template Repository: https://github.com/CameronBrooks11/just-the-docs-template-openscad

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: grey-dk
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
